[package]
name = "plum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

serde = "1.0.196"
obsidian = { path = "../plugins/plugins/obsidian" }
reqwest = "0.11.24"
zip = "0.5.11"
